# Generated by Django 3.2.3 on 2022-08-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='roles',
            new_name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(default='admin', max_length=30),
        ),
    ]
