# Generated by Django 3.2.3 on 2022-08-14 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGenderCategory',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Men'), (2, 'Women')], primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Product Gender Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Jackets'), (2, 'Shirts')], primary_key=True, serialize=False)),
                ('category', models.CharField(default='Jackets', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_image', models.ImageField(default='default.jpg', storage=products.models.product_storage_path, upload_to=products.models.product_directory_path)),
                ('secondary_image', models.ImageField(default='default.jpg', storage=products.models.product_storage_path, upload_to=products.models.product_directory_path)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10000.0)])),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
                ('colour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.colour')),
                ('gender_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productgendercategory')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size')),
            ],
        ),
    ]
