# Generated by Django 3.2.3 on 2022-08-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgendercategory',
            old_name='category',
            new_name='gender',
        ),
    ]
