# Generated by Django 3.2.3 on 2022-08-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_productgendercategory_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGenderCategory',
            new_name='Gender',
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name_plural': 'Genders'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='gender_category',
            new_name='gender',
        ),
    ]
