# Generated by Django 3.2.3 on 2021-06-12 14:39

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210609_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=products.models.product_directory_path),
        ),
        migrations.AddField(
            model_name='productgendercategory',
            name='category',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Unisex')], default=3, max_length=10),
        ),
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.CharField(choices=[(1, 'Tops'), (2, 'Bottoms'), (3, 'Dresses'), (4, 'Footwear'), (5, 'Outwear'), (6, 'Other')], default=6, max_length=10),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tops'), (2, 'Bottoms'), (3, 'Dresses'), (4, 'Footwear'), (5, 'Outwear'), (6, 'Other')], primary_key=True, serialize=False),
        ),
    ]
