# Generated by Django 3.2.3 on 2021-12-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgendercategory',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='category',
            field=models.CharField(default='Tops', max_length=20),
        ),
    ]
