# Generated by Django 3.2.3 on 2022-01-03 15:01

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211224_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productgendercategory',
            options={'verbose_name_plural': 'Product Gender Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='primary_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(default='default.jpg', upload_to=products.models.product_directory_path),
        ),
        migrations.AlterField(
            model_name='productgendercategory',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Men'), (2, 'Women')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='category',
            field=models.CharField(default='Jackets', max_length=20),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Jackets'), (2, 'Shirts')], primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.colour'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size'),
        ),
    ]
