# Generated by Django 3.2.3 on 2022-01-03 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
