# Generated by Django 3.2.3 on 2022-01-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secondary_image',
        ),
    ]
