# Generated by Django 3.2.3 on 2022-01-03 16:07

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220103_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(default='default.jpg', upload_to=products.models.product_directory_path),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(default='default.jpg', upload_to=products.models.product_directory_path),
        ),
    ]
