# Generated by Django 3.2.3 on 2022-01-04 16:06

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20220103_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(default='default.jpg', storage=products.models.product_storage_path, upload_to=products.models.product_directory_path),
        ),
    ]
