# Generated by Django 3.2.3 on 2022-08-11 03:29

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_primary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(default='default.jpg', storage=products.models.product_storage_path, upload_to=products.models.product_directory_path),
        ),
    ]
