# Generated by Django 3.2.3 on 2022-08-11 04:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20220811_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uid',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
