# Generated by Django 3.2.3 on 2022-08-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Delivery is pending'), (2, 'Delivered'), (3, 'Cancelled')], primary_key=True, serialize=False)),
                ('order_status', models.CharField(default='Delivery is pending', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Order statuses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('products', models.ManyToManyField(to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
