# Generated by Django 3.2.3 on 2021-12-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='order_status',
            field=models.CharField(default='Delivery is pending', max_length=20),
        ),
    ]
