load_fixtures:
	docker-compose exec web python3 manage.py loaddata CountryFixture.json
	docker-compose exec web python3 manage.py loaddata AddressFixture.json
	docker-compose exec web python3 manage.py loaddata OrderStatusFixture.json
	docker-compose exec web python3 manage.py loaddata BrandFixture.json
	docker-compose exec web python3 manage.py loaddata ColourFixture.json
	docker-compose exec web python3 manage.py loaddata SizeFixture.json
	docker-compose exec web python3 manage.py loaddata GenderFixture.json
	docker-compose exec web python3 manage.py loaddata ProductTypeFixture.json
	docker-compose exec web python3 manage.py loaddata RoleFixture.json
	docker-compose exec web python3 manage.py loaddata ProfileFixture.json
	docker-compose exec web python3 manage.py loaddata ProductFixture.json
